# Generated by Django 4.1.5 on 2023-02-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_subcribers_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_mo',
        ),
    ]
