# Generated by Django 4.1.5 on 2023-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_name_category_name_mo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_mo',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='subcribers',
            field=models.ManyToManyField(related_name='categories', to='blog.subscription'),
        ),
    ]
