# Generated by Django 4.1.5 on 2023-02-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_name_mo_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categorykol',
        ),
    ]
