# Generated by Django 4.1.5 on 2023-02-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_category_postcategory_categorykol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categorykol',
            new_name='category',
        ),
    ]
